#!/usr/bin/env python3
"""
test_placeholders.py — the app must emit markup its own renderer understands,
and must not end a turn on a promise.

TWO REPORTED FAILURES, from one screenshot
==========================================

1. Chat bubbles reading literally `_used web_read_`.

   That string is generated by the app (_action_summary, for a turn that
   carried only a tool call), and text_to_pango's ITALIC_RE matches `*this*`
   and NOT `_this_` — on purpose, because underscores are everywhere in the
   text this app renders (web_read, tool_result, max_tokens) and supporting
   them would italicise the middle of every other snake_case sentence.

   So the emitter and the renderer disagreed, and every status placeholder the
   app produced — `_used web_read_`, `_(thinking…)_`, `_(working…)_`,
   `_(done)_`, `_(stopped)_`, `_(error: …)_` — was shown to the operator as raw
   markdown. Nothing tested that the app's own output survived its own
   renderer, so nobody found out.

2. The turn ENDED on an announcement:

     "I've got the site and the paper metadata. Let me grab the HN discussion
      thread… and also look for a news writeup that distills it cleaner."

   …and then nothing happened, and the report never came.

   basilisk_core.reply_intends_action exists exactly to catch that, and the
   mission loop uses it — but every branch that consumes it is gated behind
   `if self._mission_active`. In ANSWER MODE (leashed, the normal way a
   question gets asked) the same reply fell straight through to
   _finish_turn_cleanup(). Answer mode's own directive tells the model to
   "chain as many reads as it takes", so a multi-step answer is the DESIGNED
   behaviour there — it just had no recovery when the model narrated the next
   step instead of calling it.

Run:  python3 tests/test_placeholders.py
"""

from __future__ import annotations

import io
import os
import re
import sys

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _ROOT)

from basilisk_core import (                                     # noqa: E402
    reply_intends_action, reply_is_strong_conclusion, looks_degraded)

_p = _f = 0


def ck(name, cond, detail=""):
    global _p, _f
    if cond:
        _p += 1
        print(f"  PASS {name}")
    else:
        _f += 1
        print(f"  FAIL {name}" + (f"   [{detail}]" if detail else ""))


SRC = io.open(os.path.join(_ROOT, "basilisk.py"), encoding="utf-8").read()

# The renderer, lifted verbatim from basilisk.py so this suite needs no GTK.
INLINE_CODE_RE = re.compile(r"`([^`\n]+)`")
BOLD_RE = re.compile(r"\*\*([^*\n]+)\*\*")
ITALIC_RE = re.compile(r"(?<!\*)\*([^*\n]+)\*(?!\*)")


def render(text: str) -> str:
    safe = (text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))
    safe = BOLD_RE.sub(r"<b>\1</b>", safe)
    safe = ITALIC_RE.sub(r"<i>\1</i>", safe)
    return INLINE_CODE_RE.sub(r"<code>\1</code>", safe)


ck("the lifted renderer matches the shipped one",
   'ITALIC_RE      = re.compile(r"(?<!\\*)\\*([^*\\n]+)\\*(?!\\*)")' in SRC)


# ── 1. every placeholder the app emits must actually render ──────────
print("\n== the app's own status text survives its own renderer ==")
PLACEHOLDERS = [
    "*used web_read*",
    "*(thinking…)*",
    "*(working…)*",
    "*(done)*",
    "*(stopped)*",
    "*(error: connection refused)*",
    "*(+2 more)*",
    "*wrote /tmp/report.md*",
    "*updated memory*",
]
for _t in PLACEHOLDERS:
    _r = render(_t)
    ck(f"renders as italics, not raw markup: {_t}",
       "<i>" in _r and "*" not in _r, repr(_r))

# The exact bubble from the screenshot must no longer be producible.
ck("no placeholder in basilisk.py still uses _underscore_ italics",
   not re.search(r'"_\([^"]*\)_"', SRC), "found an underscore placeholder")
ck("_action_summary emits asterisks",
   'parts.append("*" + p + "*")' in SRC)
ck("…including its overflow marker", '"  *(+%d more)*"' in SRC)
ck("the streaming/finished placeholders too",
   '"*(thinking…)*"' in SRC and '"*(done)*"' in SRC
   and '"*(stopped)*"' in SRC)

# And the reason the regex is asterisk-only must survive: snake_case prose in a
# normal reply must NOT come out italicised.
print("\n== snake_case prose is still not mangled ==")
for _t in ["the tool_result envelope and the max_tokens setting",
           "read /etc/shadow and check basilisk_core.py",
           "web_read returned 200 for raw.githubusercontent.com"]:
    ck(f"left alone: {_t[:44]}…", "<i>" not in render(_t), repr(render(_t)))

ck("real markdown italics still work",
   "<i>works</i>" in render("this *works* fine"))
ck("bold still works", "<b>bold</b>" in render("this is **bold**"))
ck("inline code still works", "<code>x</code>" in render("run `x` now"))


# ── 2. an announced next step must not end the turn ──────────────────
print("\n== 'let me go do X' is a stall, not an answer ==")
SCREENSHOT_REPLY = (
    "I've got the site and the paper metadata. Let me grab the HN discussion "
    "thread to see what the community is saying about the attack, and also "
    "look for a news writeup that distills it cleaner than the raw site.")

ck("the exact reply from the screenshot reads as INTENDING action",
   reply_intends_action(SCREENSHOT_REPLY) is True)
ck("…is not degraded", looks_degraded(SCREENSHOT_REPLY) is False)
ck("…and is not a conclusion",
   reply_is_strong_conclusion(SCREENSHOT_REPLY) is False)

for _s in ["Let me grab the HN thread and check the news writeup.",
           "I'll run a scan on that host now.",
           "Next I'll read the paper and summarise it.",
           "Now let me look up the CVE details."]:
    ck(f"stall detected: {_s[:46]}", reply_intends_action(_s) is True)

for _s in ["Reasoning-trace extraction works by querying the model repeatedly "
           "and reconstructing the intermediate steps; the paper reports 87% "
           "fidelity. Source: arxiv.org/abs/2508.1234.",
           "Done. Nothing further.",
           "The host is up; ports 22 and 80 are open. That's the full picture."]:
    ck(f"real answer NOT flagged: {_s[:42]}…",
       reply_intends_action(_s) is False)

# ── the wiring itself ──
print("\n== the recovery is wired into answer mode, not just missions ==")
ck("a bound exists", "ANSWER_STALL_NUDGE_MAX" in SRC)
ck("…and it is small (a couple of pushes, not a loop)",
   re.search(r"ANSWER_STALL_NUDGE_MAX = ([1-3])\b", SRC) is not None,
   "bound missing or too large")
ck("the counter is reset per request",
   "self._answer_stall_nudges = 0" in SRC)
ck("the nudge is reached OUTSIDE the `_mission_active` branch",
   "_answer_stall_nudges" in SRC.split("if self._mission_active and not cancelled:")[-1])
ck("it tells the model plainly that nothing ran",
   "did not emit a tool call" in SRC and "NOTHING RAN" in SRC)
# The nudge's guard clause, as one flat string. Source-level checks must not
# assume where a concatenated literal happens to wrap — an earlier draft of
# this file asserted "emit the tool call now" and failed because the sentence is
# split across two adjacent string literals, which is a property of the
# formatter, not of the code.
# ANCHORED ON THE BLOCK ITSELF, not on a fixed width from the section
# header. The original sliced 2600 chars after the section comment and broke
# the day the deterministic plan/verification gates were added between the
# two — the code was correct and the test measured a distance. A named
# anchor cannot be pushed out of range by a neighbour growing.
_ANCHOR = "ANSWER-MODE STALL NUDGE (the block below is this one)"
_NUDGE_BLOCK = (SRC.split(_ANCHOR, 1)[1][:2600] if _ANCHOR in SRC else "")
ck("the nudge block is findable by its own comment anchor", bool(_NUDGE_BLOCK))
_FLAT = re.sub(r'"\s*\n\s*"', "", SRC)      # join adjacent string literals

ck("…and offers the two valid moves",
   "emit the tool call now" in _FLAT and "complete final answer" in _FLAT)
ck("it never fires on a cancelled/stopped turn",
   "not cancelled and not executable" in _NUDGE_BLOCK
   and "not self._stop_requested" in _NUDGE_BLOCK, repr(_NUDGE_BLOCK[-300:]))
ck("…nor once tools are locked",
   "not self._tools_locked" in _NUDGE_BLOCK)
ck("…nor on a degraded reply (that path has its own retry)",
   "not looks_degraded(final)" in _NUDGE_BLOCK)

print(f"\nplaceholders: {_p} passed, {_f} failed")
sys.exit(1 if _f else 0)
